### ISSUE TITLE
add arc42 favicon

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42.github.io#11]
... that can also be used in css-class to precede header text...

**Comment by gernotstarke** [comment]
see http://callmenick.com/post/using-css-icons-to-spice-up-your-design

**Comment by rdmueller** [comment]
Yeah! An SVG version of the logo would be great!

**Comment by gernotstarke** [comment]
included an svg logo in docs.arc42.org: /assets/img/arc42-favicon.svg

**Comment by gernotstarke** [comment]
oops - closed for wrong site - reopen

**Comment by gernotstarke** [comment]
already done for arc42.org...
